Projeto extensionista  do curso Tópicos de Big Data em Python
Faculdate Estacio de Sá RJ (Unesa)
Aluno: José Roberto Duarte Hegendorne
Matrícula: 202502214154
Curso Presencial
Professora: Simone Gama
Período: 1ª semestre 2026

Dados do Sistema de Bilhetagem Eletrônica

URL dos dados analizados: 
https://dadosabertos.rj.gov.br/dataset/setram_sbe

Repositório de dados baixados https://dadosabertos.rj.gov.br/dataset/setram_sbe
link do repósitorio do drive é  https://drive.google.com/drive/folders/1486i6aBSUVuyrD6bISm0qYGZs-eIhK71?usp=sharing

os arquivos são distribuidos com a movimentação diaria do bilhete unico, fazer o carregamento disso, em grandes periodos , requer um hardware com mais recursos


Dicionario de Dados dos arquivos originais: 
    Cartão Hash: 
        Sequência única de caracteres gerada a partir do Nº Cartão. 
    Data da Transação:
        Data e hora do processamento da transação.
    Data do Processamento:  
        Data e hora do processamento da transação.
    Descrição da Aplicação:    
        Código da aplicação do cartão 
            - 100 - Expresso
            - 114 - Siga Viagem Supervia, 
            - 115 - Siga Viagem Metrô, 
            - 400 - Vale-transporte, 
            - 450 - Empresarial, 
            - 820 - Gratuidade de Morador de Paquetá/Ilha Grande, 
            - 80 QRCode Unitário
        Descrição da Aplicação
    Linha - 
        Número e nome da Linha.
    Nº Carro:
         Número da estação ou do carro onde a transação foi realizada.
    Nº Cartão:
        Número externo do cartão do usuário. Informação anonimizada para atender a LGPD, conforme exemplo a seguir: 1091xxxxxx713.
    Nº Validador:
        Número do validador utilizado na transação.
    Operadora:
          Nome da Operadora de transporte. Informação anonimizada para as Vans para atender a LGPD, conforme exemplo a seguir: VAN560001-LUISA MAxxxxxxxx
    Sentido:
        Código do sentido da linha (0 - não informado, 1 - ida, 2 - volta).
    Sindicato:
        Nome do sindicato
    Vl Linha
        Valor da linha da operadora de transporte.
    Vl Subsídio
        Valor do subsídio.
    Vl Trans
        Valor descontado no cartão do usuário.
 
    
      


Variaveis declaradas:
    Po - pandas (referente ao panda do filme , po)
    Bu_total - com todos os campos
    Bu - (DataFrame) bilhete unico tratado

In [1]:
#iniciando carregamento da biblioteca pandas e instanciando na variavel Po
import pandas as Po

 Fazendo carregamento do ARQUIVO CSV
 a separação dos dados esta sendo feito por ";"

In [2]:
#carregando o arquivo na variavel Bu (bilhete unico)
#tudo
#Bu_total = Po.read_csv(r"i:\facul\csv\transacao_be_publico_2026_03_15.csv\TRANSACAO_BE_PUBLICO_2026_03_15.csv", encoding='utf8', sep=';')
# com 5000
Bu_total = Po.read_csv(r"i:\facul\csv\transacao_be_publico_2026_03_15.csv\TRANSACAO_BE_PUBLICO_2026_03_15.csv", encoding='utf8', sep=';',nrows=5000)
Bu_total.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Data do Processamento   5000 non-null   str
 1   Data da Transação       5000 non-null   str
 2   Nº Cartão               5000 non-null   str
 3   Cartão Hash             5000 non-null   str
 4   Descrição da Aplicação  5000 non-null   str
 5   Sindicato               5000 non-null   str
 6   Operadora               5000 non-null   str
 7   Linha                   5000 non-null   str
 8   Nº Carro                5000 non-null   int64
 9   Sentido                 0 non-null      float64
 10  Nº Validador            5000 non-null   int64
 11  Vl Linha                5000 non-null   str
 12  Vl Trans                5000 non-null   str
 13  Vl Subsídio             0 non-null      float64
dtypes: float64(2), int64(2), str(10)
memory usage: 547.0 KB

 Removendo os campos  com valores nulos usando dropna()

In [3]:
#Bu_total = Bu_total.dropna()

Estou estruturando os campos do arquivo CSV à serem tratados, Removi rash e o numero do cartão do passageiro porque eles esconderam o numero real com caracteres X
Nº  2024XXXXX3128

In [4]:
colunas = [
    "Data do Processamento",    
    "Data da Transação",
    "Descrição da Aplicação",
    "Sentido",
    "Nº Validador",
    "Sindicato",
    "Operadora",
    "Linha",
    "Nº Carro",
    "Nº Validador",
    "Vl Linha",
    "Vl Trans",
    "Vl Subsídio"
]


#colocando os campos necessarios na variavel Bu
Bu = Bu_total[colunas].dropna()

# tratando os campos que contém data. pois o formato esta em string
#  mudou o padrão de XX / XX / XXXX para xx-xx-xxxx  

Bu["Data do Processamento"] = Po.to_datetime(Bu["Data do Processamento"], dayfirst=True) #este funcionou
Bu["Data da Transação"] = Po.to_datetime(Bu["Data da Transação"], dayfirst=True) #este funcionou


# trocando a vírgula por ponto  vl linhas , vl Trans e vl subsídio  pois estou tratando com valores numéricos

#Bu.loc[:,"Vl Linha"] = Bu["Vl Linha"].str.replace(",", ".").astype(float)
#Bu.loc[:,"Vl Trans"] = Bu["Vl Trans"].str.replace(",", ".").astype(float)
Bu["Vl Linha"] = Bu["Vl Linha"].str.replace(",", ".").astype(float)
Bu["Vl Trans"] = Bu["Vl Trans"].str.replace(",", ".").astype(float)

# ==================================================================================== 
# ==================================================================================== 
# ====================================================================================

Aqui estou salvando arquivo tratado para deixar mais enxuto para pequenos testes

In [5]:
#Bu.to_csv(r"F:\python\bigdata\csv\dados_tratados_Bu.csv", index=False)

Mostra informações gerais do DataFrame (tipos de dados, valores não nulos, etc.)

In [6]:
Bu.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Data do Processamento   0 non-null      datetime64[s]
 1   Data da Transação       0 non-null      datetime64[s]
 2   Descrição da Aplicação  0 non-null      str
 3   Sentido                 0 non-null      float64
 4   Nº Validador            0 non-null      int64
 5   Sindicato               0 non-null      str
 6   Operadora               0 non-null      str
 7   Linha                   0 non-null      str
 8   Nº Carro                0 non-null      int64
 9   Nº Validador            0 non-null      int64
 10  Vl Linha                0 non-null      float64
 11  Vl Trans                0 non-null      float64
 12  Vl Subsídio             0 non-null      float64
dtypes: datetime64[s](2), float64(4), int64(3), str(4)
memory usage: 132.0 bytes

Aqui estou mostrando as primeiras linhas

In [7]:
Bu.head()

Empty DataFrame
Columns: [Data do Processamento, Data da Transação, Descrição da Aplicação, Sentido, Nº Validador, Sindicato, Operadora, Linha, Nº Carro, Nº Validador, Vl Linha, Vl Trans, Vl Subsídio]
Index: []

Resumo Estático pelo metodo .describe()

Count -> esta contando o numero de registros onde eu limitei dentro do read_csv  coloquei um nrows = 5000
mean -> esta tirando média
std  -> desvio padrao  (o quanto os valores estão espalhados em relação à média.) 
min - > valor Minimo
25% ->  primeiro quartil
50% ->  mediana
75% = > terceiro quartil
Max - e o maximo

In [8]:
Bu = Bu.dropna()
Bu.describe().round(2) #round(2) é pra limitar as casas decimais depois do ponto

,Data do Processamento,Data da Transação,Sentido,Nº Validador,Nº Carro,Nº Validador,Vl Linha,Vl Trans,Vl Subsídio
count,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Numero de passageiros por cada concessionaria de transporte publico

In [9]:
Bu["Operadora"].value_counts()

Series([], Name: count, dtype: int64)

Abaixo lista o gasto

In [10]:
Bu["Linha"].value_counts()

Series([], Name: count, dtype: int64)

Abaixo valor de quanto cada veiculo produziu

In [11]:
# Agrupando por linha para ver faturamento e total de passageiros
analise_linha = Bu.groupby('Linha').agg(
    Faturamento_Total=('Vl Trans', 'sum'),
    Total_Passageiros=('Vl Trans', 'count'),
    Qtd_Veiculos_Unicos=('Nº Carro', 'nunique') # Conta quantos carros diferentes operaram na linha
).reset_index()
analise_linha

Empty DataFrame
Columns: [Linha, Faturamento_Total, Total_Passageiros, Qtd_Veiculos_Unicos]
Index: []

In [12]:
Bu["Nº Carro"].value_counts()

Series([], Name: count, dtype: int64)

Contando quantas vezes um validador se repete

In [13]:
Bu["Nº Validador"].value_counts()

ValueError: Grouper for 'Nº Validador' not 1-dimensional

In [ ]:
Po.crosstab(Bu["Operadora"], Bu["Sindicato"])