Este Projeto extensionista  Faculdate Estacio de Sá RJ (Unesa)
Aluno: José Roberto Duarte Hegendorne
Matrícula: 202502214154
Curso Presencial
Período: 1ª semestre 2026

Tratando dados do bilhete unico
importando a biblioteca panda

Variaveis declaradas:

Po - pandas (referente ao panda do filme , po)
Bu_total - com todos os campos
Bu - (DataFrame) bilhete unico tratado

Estou fazendo leitura do arquivo extraido do sistema dados abertos do governo do estado do rio de janeiro
#link do repósitorio do drive é  https://drive.google.com/drive/folders/1486i6aBSUVuyrD6bISm0qYGZs-eIhK71?usp=sharing

os arquivos são distribuidos com a movimentação diaria do bilhete unico, fazer o carregamento disso, em grandes periodos , requer um hardware com mais recursos

In [130]:
#iniciando carregamento da biblioteca pandas e instanciando na variavel Po
import pandas as Po

 Fazendo carregamento do ARQUIVO CSV

In [131]:
#carregando o arquivo na variavel Bu (bilhete unico)
#tudo
#Bu_total = Po.read_csv(r"i:\facul\csv\transacao_be_publico_2026_03_15.csv\TRANSACAO_BE_PUBLICO_2026_03_15.csv", encoding='utf8', sep=';')
# com 5000
Bu_total = Po.read_csv(r"i:\facul\csv\transacao_be_publico_2026_03_15.csv\TRANSACAO_BE_PUBLICO_2026_03_15.csv", encoding='utf8', sep=';',nrows=5000)

 Removendo os campos  com valores nulos usando dropna()

In [132]:
#Bu_total = Bu_total.dropna()

estou estruturando os campos do arquivo CSV à serem tratados, listando as colunas que trabalharei.

In [133]:
colunas = [
    "Data do Processamento",
    "Data da Transação",
    "Sindicato",
    "Operadora",
    "Linha",
    "Nº Carro",
    "Nº Validador",
    "Vl Linha",
    "Vl Trans"
]


#colocando os campos necessarios na variavel Bu
Bu = Bu_total[colunas].dropna()

# tratando os campos que contém data. pois o formato esta em string
#  mudou o padrão de XX / XX / XXXX para xx-xx-xxxx  

Bu["Data do Processamento"] = Po.to_datetime(Bu["Data do Processamento"], dayfirst=True) #este funcionou
Bu["Data da Transação"] = Po.to_datetime(Bu["Data da Transação"], dayfirst=True) #este funcionou


# trocando a vírgula por ponto  vl linhas , vl Trans e vl subsídio  pois estou tratando com valores numéricos

#Bu.loc[:,"Vl Linha"] = Bu["Vl Linha"].str.replace(",", ".").astype(float)
#Bu.loc[:,"Vl Trans"] = Bu["Vl Trans"].str.replace(",", ".").astype(float)
Bu["Vl Linha"] = Bu["Vl Linha"].str.replace(",", ".").astype(float)
Bu["Vl Trans"] = Bu["Vl Trans"].str.replace(",", ".").astype(float)

# ==================================================================================== 
# ==================================================================================== 
# ====================================================================================

Aqui estou salvando arquivo tratado para deixar mais enxuto para pequenos testes

In [134]:
#Bu.to_csv(r"F:\python\bigdata\csv\dados_tratados_Bu.csv", index=False)

Mostra informações gerais do DataFrame (tipos de dados, valores não nulos, etc.)

In [135]:
Bu.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Data do Processamento  5000 non-null   datetime64[us]
 1   Data da Transação      5000 non-null   datetime64[us]
 2   Sindicato              5000 non-null   str
 3   Operadora              5000 non-null   str
 4   Linha                  5000 non-null   str
 5   Nº Carro               5000 non-null   int64
 6   Nº Validador           5000 non-null   int64
 7   Vl Linha               5000 non-null   float64
 8   Vl Trans               5000 non-null   float64
dtypes: datetime64[us](2), float64(2), int64(2), str(3)
memory usage: 351.7 KB

Aqui estou mostrando as primeiras linhas

In [136]:
Bu.head()

,Data do Processamento,Data da Transação,Sindicato,Operadora,Linha,Nº Carro,Nº Validador,Vl Linha,Vl Trans
0,2026-03-15 15:54:08,2026-03-15 15:54:08,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,17007,77399,5.0,5.0
1,2026-03-15 22:42:20,2026-03-15 22:42:20,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L2 PVN - Estação Pavuna - Metrô,32208,77688,7.9,7.9
2,2026-03-15 08:13:28,2026-03-15 08:13:28,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L1 SCP - Estação Siqueira Campos - Metrô,17214,77361,7.9,7.9
3,2026-03-15 09:50:49,2026-03-15 09:50:49,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,13006,77536,5.0,5.0
4,2026-03-15 09:18:08,2026-03-15 09:18:08,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,13006,77536,5.0,5.0

Resumo Estático pelo metodo .describe()

Count -> esta contando o numero de registros onde eu limitei dentro do read_csv  coloquei um nrows = 5000
mean -> esta tirando média
std  -> desvio padrao  (o quanto os valores estão espalhados em relação à média.) 
min - > valor Minimo
25% ->  primeiro quartil
50% ->  mediana
75% = > terceiro quartil
Max - e o maximo

In [137]:
Bu = Bu.dropna()
Bu.describe().round(2) #round(2) é pra limitar as casas decimais depois do ponto

,Data do Processamento,Data da Transação,Nº Carro,Nº Validador,Vl Linha,Vl Trans
count,5000,5000,5000.00,5000.00,5000.00,5000.00
mean,2026-03-15 13:59:12.736000,2026-03-15 13:59:12.736000,20593.60,76297.05,6.63,6.63
min,2026-03-15 00:01:09,2026-03-15 00:01:09,1208.00,42001.00,5.00,5.00
25%,2026-03-15 10:34:10.750000,2026-03-15 10:34:10.750000,11207.00,77108.00,5.00,5.00
50%,2026-03-15 14:05:06.500000,2026-03-15 14:05:06.500000,16109.00,77397.00,7.90,7.90
75%,2026-03-15 17:21:18.250000,2026-03-15 17:21:18.250000,29107.00,77524.00,7.90,7.90
max,2026-03-15 23:58:01,2026-03-15 23:58:01,72305.00,78329.00,7.90,7.90
std,NaN,NaN,15601.56,5395.36,1.44,1.44

Numero de passageiros por cada concessionaria de transporte publico

In [138]:
Bu["Operadora"].value_counts()

Operadora
Concessao Metroviaria do Rio de Janeiro S. A.    2803
Barcas Rio                                       2197
Name: count, dtype: int64

Abaixo lista o gasto

In [139]:
Bu["Linha"].value_counts()

Linha
PXV-PQ - PRAÇAXV X PAQUETA                         1540
L2 PVN - Estação Pavuna - Metrô                     656
PXV-NIT - PRAÇA XV X ARARIBOIA                      653
L1 CTR - Estação Central - Metrô                    536
L4 JOC - Estação Jardim Oceânico                    228
L1 CNL - Estação Cinelândia - Metrô                 197
L1 GNO - Estação General Osório - metrô             135
L1 CAV - Estação Cardeal Arcoverde - Metrô          126
L1 BTF - Estação Botafogo - Metrô                    66
L1 LMC - Estação Largo do Machado - Metrô            66
L1 GLR - Estação Glória - Metrô                      63
L4 JAH - Estação Jardim de Alah                      54
L2 DCT - Estação Del Castilho - Metrô                53
L4 NSP - Estação Nossa Senhora da Paz                48
L1 SCP - Estação Siqueira Campos - Metrô             47
L1 CTG - Estação Cantagalo - Metrô                   44
L2 MRC - Estação Maracanã - Metrô                    39
L2 CNT - Estação Coelho Neto - Metrô                 39
L1 CTT - Estação Catete - Metrô                      38
L4 SCO - Estação São Conrado                         36
L2 IRJ - Estação Irajá - Metrô                       32
L2 SCR - Estação São Cristovão - Metrô               32
L1 URG - Estação Uruguaiana - Metrô                  28
L2 INH - Estação Inhaúma - Metrô                     26
L1 SPN - Estação Saens Peña - Metrô                  25
L2 MGR - Estação Maria da Graça - Metrô              24
L2 AFB - Estação Acari Fazenda Botafogo - Metrô      22
L1 CRC - Estação Carioca - Metrô                     21
L1 FLA - Estação Flamengo - Metrô                    19
L1 ESA - Estação Estácio - Metrô                     16
L1 AFP - Estação Afonso Pena - Metrô                 11
L2 CLG - Estação Colégio - Metrô                     11
L2 CNO - Estaçao Cidade Nova - metrô                 11
L2 VCV - Estação Vicente de Carvalho - Metrô         10
L4 AQT - Estação Antero de Quental                   10
L2 ERN - Estação Engenho da Rainha - Metrô            9
L1 URI - Estação Uruguai - Metrô                      8
L1 POZ - Estação Praça Onze - Metrô                   5
L2 TCL - Estação Thomaz Coelho - Metrô                4
MAN-IGD - MANGARATIBA X I.GRANDE                      4
L1 PVG - Estação Presidente Vargas - Metrô            2
L1 SFX - Estação São Francisco Xavier - Metrô         2
L2 ERP - Estação Eng Rubens Paiva - Metrô             2
L2 TRG - Estação Triagem - Metrô                      2
Name: count, dtype: int64

Conta quantidade de passageiros que usou o mesmo transporte

In [140]:
Bu["Nº Carro"].value_counts()

Nº Carro
13005    387
13006    355
6115     219
17008    186
32208    180
        ...
8305       1
17210      1
14009      1
19212      1
72119      1
Name: count, Length: 176, dtype: int64

Contando quantas vezes um validador se repete

In [146]:
Bu["Nº Validador"].value_counts()

Nº Validador
78329    387
77536    355
77364    219
77444    186
77688    180
        ...
75215      1
77111      1
74928      1
77458      1
77103      1
Name: count, Length: 176, dtype: int64

In [147]:
Bu

,Data do Processamento,Data da Transação,Sindicato,Operadora,Linha,Nº Carro,Nº Validador,Vl Linha,Vl Trans
0,2026-03-15 15:54:08,2026-03-15 15:54:08,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,17007,77399,5.0,5.0
1,2026-03-15 22:42:20,2026-03-15 22:42:20,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L2 PVN - Estação Pavuna - Metrô,32208,77688,7.9,7.9
2,2026-03-15 08:13:28,2026-03-15 08:13:28,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L1 SCP - Estação Siqueira Campos - Metrô,17214,77361,7.9,7.9
3,2026-03-15 09:50:49,2026-03-15 09:50:49,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,13006,77536,5.0,5.0
4,2026-03-15 09:18:08,2026-03-15 09:18:08,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,13006,77536,5.0,5.0
...,...,...,...,...,...,...,...,...,...
4995,2026-03-15 09:29:11,2026-03-15 09:29:11,BARCAS,Barcas Rio,PXV-NIT - PRAÇA XV X ARARIBOIA,14018,76910,5.0,5.0
4996,2026-03-15 08:12:16,2026-03-15 08:12:16,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L1 CTR - Estação Central - Metrô,6116,77439,7.9,7.9
4997,2026-03-15 10:26:43,2026-03-15 10:26:43,BARCAS,Barcas Rio,PXV-NIT - PRAÇA XV X ARARIBOIA,14018,76910,5.0,5.0
4998,2026-03-15 10:58:10,2026-03-15 10:58:10,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L1 CTR - Estação Central - Metrô,6117,42170,7.9,7.9
4999,2026-03-15 18:52:17,2026-03-15 18:52:17,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L4 NSP - Estação Nossa Senhora da Paz,52104,76843,7.9,7.9